const SHOW_LOADING = 'SHOW_LOADING';
const HIDE_LOADING = 'HIDE_LOADING';
const SHOW_NOTIFICATION = 'SHOW_NOTIFICATION';
const HIDE_NOTIFICATION = 'HIDE_NOTIFICATION';
const SET_THEME = 'SET_THEME';
const SET_NAVIGATION_DATA = 'SET_NAVIGATION_DATA';
const TOGGLE_MENU = 'TOGGLE_MENU';
const SHOW_LIST = 'SHOW_LIST';
const SELECTED_LIST = 'SELECTED_LIST';
const CART_ITEMS = 'CART_ITEMS';
const REMOVE_ITEM = 'REMOVE_ITEM';
export {
    SHOW_LOADING,
    HIDE_LOADING,
    SHOW_NOTIFICATION,
    SELECTED_LIST,
    REMOVE_ITEM,
    HIDE_NOTIFICATION,
    SET_THEME,
    CART_ITEMS,
    SET_NAVIGATION_DATA,
    TOGGLE_MENU,
    SHOW_LIST
}